server:
  port: 8080

feign:
  client:
    config:
      demo-open-feign-provider:
        connectTimeout: 5000
        read-timeout: 5000

provider:
  name: demo-open-feign-provider

spring:
  application:
    name: demo-open-feign-consumer