server:
  port: 9527
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: eureka-client
          uri: http://localhost:8080
          predicates:
            - Path=/
            - Method=GET
eureka:
  instance:
    instance-id: gateway1
    hostname: gateway
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8761/eureka