server:
  port: 8080
feign:
  client:
    config:
      feignName:
        connectTimeout: 5000
        read-timeout: 5000
        logger-level: full
store:
  provider:
    name: demo-open-feign-provider

spring:
  application:
    name: demo-open-feign-consumer