server:
  port: 7777
eureka:
  client:
    register-with-eureka: true #服务消费者可以不向服务注册中心注册服务
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true  #服务消费者客户端需要去检索服务
  instance:
    appname: open-feign-client
feign:
  client:
    config:
      feignName:
        connectTimeout: 5000
        read-timeout: 5000
        logger-level: full
spring:
  application:
    name: open-feign-client